### ISSUE TITLE
Better syntax errors

### ISSUE THREAD

**Issue by ai** [postcss/postcss-selector-parser#104]
[Current syntax error](https://github.com/facebookincubator/create-react-app/issues/1926) are not so welcome as in PostCSS core. If we will generate postcss’s `CssSyntaxError`, it will be much better (with code frame and source map support).

@ben-eb If you don’t have time, I can send guys from Cult of Martians, just write short instruction where to look.

**Comment by ben-eb** [comment]
You are correct, I have enough to do. 🙂

Problem with code frame is that we only parse the selector string, but there are better ways of showing this. I haven't merged this PR because it isn't as useful as a formatted error: https://github.com/postcss/postcss-selector-parser/pull/35

**Comment by ben-eb** [comment]
https://github.com/postcss/postcss-selector-parser/releases/tag/v3.0.0-rc.0
