### ISSUE TITLE
Support reference combinators

### ISSUE THREAD

**Issue by evilebottnawi** [postcss/postcss-selector-parser#106]
Ref: https://github.com/stylelint/stylelint/issues/2506. I can do PR if your accept.

**Comment by ben-eb** [comment]
Right now I'm focusing on PostCSS 6 work so I don't have much time to look into this. https://github.com/postcss/postcss-selector-parser/pull/105#issuecomment-294365917

**Comment by ben-eb** [comment]
Alright, we can look into doing a new major version. 👍

**Comment by evilebottnawi** [comment]
@ben-eb oh, forgot, we don't should be directly support `/deep/`, now it is deprecated, but be good support `/some/`, it is reference combinators

**Comment by ben-eb** [comment]
@evilebottnawi Are you still willing to send a pull request? 😄

**Comment by evilebottnawi** [comment]
@ben-eb No time now :disappointed:  I can start this later.

**Comment by ben-eb** [comment]
@evilebottnawi I'd like to get 3.0 out this week, is this support critical for your use case? If so it'd be great if you could send a patch to the 3.0 branch.

https://github.com/postcss/postcss-selector-parser/tree/3.0

**Comment by evilebottnawi** [comment]
@ben-eb not critical, we have workaround for this in `stylelint`

**Comment by chriseppstein** [comment]
The reference combinator has been removed from the latest editors draft of the css-selectors level 4, specification.

https://drafts.csswg.org/selectors-4/
