### ISSUE TITLE
Error: Unexpected "space" found

### ISSUE THREAD

**Issue by svipben** [postcss/postcss-selector-parser#108]
Hello,

I get this error:
`
messageService.ts:126Error: Unexpected "space" found.     at new error (/home/svipben/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/postcss-selector-parser/dist/processor.js:29:23)     at Parser.error (/home/svipben/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/postcss-selector-parser/dist/parser.js:234:15)     at Parser.pseudo (/home/svipben/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/postcss-selector-parser/dist/parser.js:362:18)     at Parser.parse (/home/svipben/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/postcss-selector-parser/dist/parser.js:551:22)     at Parser.loop (/home/svipben/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/postcss-selector-parser/dist/parser.js:519:18)     at new Parser (/home/svipben/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/postcss-selector-parser/dist/parser.js:104:21)     at Processor.process (/home/svipben/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/postcss-selector-parser/dist/processor.js:26:21)     at resolvedNestedSelector.forEach.resolvedSelector (/home/svipben/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/stylelint/lib/rules/selector-max-compound-selectors/index.js:76:55)     at Array.forEach (native)     at rule.selectors.forEach.selector (/home/svipben/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/stylelint/lib/rules/selector-max-compound-selectors/index.js:74:48)e.doShow @ messageService.ts:126
`

I'm using this `.css`:
```
body {
  margin: 0;
  padding: 0;
}

.app {
  text-align: center;
}

.hero {
  background: #222;
  width: 100%;
  height: 150px;
}

.git {
  font-size: xx-large;
  display: inline-block;
  position: relative;
  top: 50%;
  transform: translateY(-50%);
  text-decoration: none;
  color: #ddd;

  &:hover,
  &:active {
    color: white;
  }
}

.content {
  margin: 14px;

  & .large-text {
    font-size: x-large;
  }
}

code {
  background: #eff0f1;
}
```

Try to write `:` symbol, for e.g. `:root` at the top and you will be able to reproduce this error.

This is with VS Code plugin https://marketplace.visualstudio.com/items?itemName=shinnn.stylelint, which is using `postcss-selector-parser` and the problem isn't with plugin, but with this parser.

**Comment by ben-eb** [comment]
Hello,

This is due to the parser not finding anything after a colon, and is supposed to warn you of these invalid cases (amongst others):

```css
b: c {}
b:"c" {}
```

What is happening here is that your linter might be a little eager to run before you had a chance to fill in the rest of the selector string (thus, unexpected space). If there's an option to delay the checking by some `ms` value then I'd try that. But the behaviour here is correct. 😄 

I'm going to make the message a bit clearer in 3.0, and if the consumer is passing a PostCSS node instead we will throw a `CssSyntaxError`, which can show the relevant part of the source code.

**Comment by ben-eb** [comment]
https://github.com/postcss/postcss-selector-parser/releases/tag/v3.0.0-rc.0
