### ISSUE TITLE
Handling of Less interpolation

### ISSUE THREAD

**Issue by jwilsson** [postcss/postcss-selector-parser#109]
Hi!
I don't know if this might be out of scope but ID and class selectors containing [Less Variable Interpolations](http://lesscss.org/features/#variables-feature-variable-interpolation) is parsed a bit oddly. It's picking up the ID/class but then treats the rest as a tag.

For example:
```less
.@{foo}
```

gives this AST:
```
Selector {
  spaces: { before: '', after: '' },
  nodes:
   [ ClassName {
       value: '',
       source: [Object],
       sourceIndex: 0,
       spaces: [Object],
       type: 'class',
       parent: [Circular] },
     Tag {
       value: '@{foo}',
       source: [Object],
       sourceIndex: 2,
       spaces: [Object],
       type: 'tag',
       parent: [Circular] } ],
  type: 'selector',
  parent:
   Root {
     spaces: { before: '', after: '' },
     nodes: [ [Circular] ],
     type: 'root' } }
```

Note the first `ClassName` with an empty `value` and then a `Tag` with the rest as its `value`. 

BTW, I did find #52 which is basically the same thing and I'll be happy to submit a PR fixing this issue.

**Comment by ben-eb** [comment]
Alright, we can look into doing a new major version. 👍
