### ISSUE TITLE
toString for qualified id with a namespace

### ISSUE THREAD

**Issue by jeddy3** [postcss/postcss-selector-parser#111]
When `toString()`ing a selector containing a id selector that is qualified by a type selector _which has a namespace_, the namespace is seemingly added before the id selector. I think that's the correct terminology, I was quite sure how to describe it :)

With:

```js
const selectorParser = require("postcss-selector-parser") // @2.2.3
const result = selectorParser().process("namespace|type#qualified_id").result;
console.log(result.toString());
```

Expected Result:

```shell
namespace|type#qualified_id
```

Actual Result:

```shell
namespace|typenamespace|#qualified_id
```

Is this the intended behaviour? I have to admit I'm not very familiar with namespaces.

Ref: https://github.com/stylelint/stylelint/pull/2715

**Comment by ben-eb** [comment]
It's not intended, but will be fixed in 3.0. Thanks for reporting! 😄
