### ISSUE TITLE
Why each method is too complex?

### ISSUE THREAD

**Issue by stepancar** [postcss/postcss-selector-parser#113]
Hello, thank you for this Project
I have question
https://github.com/postcss/postcss-selector-parser/blob/4ea800d17fb120db02388c65bd45e990f688dbb7/src/selectors/container.js#L105
why its so complex?
why not just this.nodes.foreach ?
Also, see https://github.com/postcss/postcss-nested/pull/57
This issue relates to each method implementation.

**Comment by ben-eb** [comment]
`each` allows you to maintain iteration whilst changing the length of the `nodes`, so it's not equivalent to `forEach`. If we swap the implementation you can see that these tests fail:

* https://github.com/postcss/postcss-selector-parser/blob/master/src/__tests__/container.js#L17
* https://github.com/postcss/postcss-selector-parser/blob/master/src/__tests__/container.js#L45

**Comment by stepancar** [comment]
@ben-eb, thank you for your answer. Could you please give a look to https://github.com/postcss/postcss-nested/pull/57 .

**Comment by ben-eb** [comment]
Did you try the tests against the original code? Note that it's OK to have more than one way of doing things, this is the nature of programming & abstractions.
