### ISSUE TITLE
Wrong stringifying of namespaced tag and selector

### ISSUE THREAD

**Issue by ai** [postcss/postcss-selector-parser#114]
Origin issue: https://github.com/postcss/postcss-nested/issues/60

Current behavior:

```js
parser().process('ui|dock.class').res.first.toString() //=> "ui|dockui|.class"
```

Expected behavior:

```js
parser().process('ui|dock.class').res.first.toString() //=> "ui|dock.class"
```

**Comment by ben-eb** [comment]
I think it's this issue? https://github.com/postcss/postcss-selector-parser/issues/111

**Comment by ai** [comment]
Yeap :) ETA of 3.0?

**Comment by ben-eb** [comment]
I'd like stylelint to report any issues they have and then we can cut 3.0. https://github.com/stylelint/stylelint/issues/2757
