### ISSUE TITLE
Value `#{$variable}` parsed incorrectly in v3.0.0-rc0

### ISSUE THREAD

**Issue by EECOLOR** [postcss/postcss-selector-parser#119]
`[class^=#{$variable}] { }` result in the `value` and `raws.unquoated` being parsed as `#{`.

One of the issues from: stylelint/stylelint#2757

**Comment by chriseppstein** [comment]
This is non-standard syntax.

**Comment by EECOLOR** [comment]
@chriseppstein I appreciate your response and probably agree with you. The previous version of this library however supported this syntax. So if the goal is to only support standard syntax, I think it's best to mention in the README that for the new version.
