### ISSUE TITLE
Attribute raw values override changes to the original.

### ISSUE THREAD

**Issue by chriseppstein** [postcss/postcss-selector-parser#122]
If an attribute's operator is changed without changing the corresponding raw attribute, then the stringification of the selector will appear unchanged. Similarly if an attribute node is changed from case insensitive to normal.

Expected: changing canonical values clears the corresponding raw value.

Work-around: dev must set unset the raw value manually.

**Comment by EECOLOR** [comment]
You also could adjust the behavior of stringification. I would not be suprised if a "selector parser" would have a toString method that would remove excessive whitespace and other formatting. It seems to me (but I am very naive as to the actual uses) that a "selector parser" is mostly used for parsing and will probably not be blamed if it had a to string function that removed formatting.

**Comment by chriseppstein** [comment]
@EECOLOR I made it work correctly for the main attribute values. For now, devs who want to muck with the spaces can dig in a bit. And I agree, I think whitespace handling is an output operation, but it is currently handles during parsing. I probably won't do much more on this front for a while.

Fixed by e35949fa7619a4d51bf4f10b170344c3dc98efa8
