### ISSUE TITLE
Type definition and sync processing

### ISSUE THREAD

**Issue by pmdartus** [postcss/postcss-selector-parser#126]
The type definition doesn't work properly with the example given in the Quick Start

```ts
import * as parser from 'postcss-selector-parser';

const transform = selectors => {
    selectors.walk(selector => {
        // do something with the selector
        console.log(String(selector))
    });
};

const transformed = parser(transform).processSync('h1, h2, h3');
//                                                ^ Argument of type '"h1, h2, h3"' is not assignable to parameter of type 'never'.
```

While async methods on parser are properly typed, all the sync methods throw a type error, because they expect a `never` type. In the meantime, it's possible to cast the parser to `parser.Processor` to avoid running into this issue.

@chriseppstein What do you think about relaxing the types for the sync APIs?

**Comment by chriseppstein** [comment]
A synchronous function passed to parser was being incorrectly inferred to be async.

```ts
type AsyncProcessor<Transform = void> = (root: parser.Root) => Transform | PromiseLike<Transform>;
```

The fix was to change this to:

```ts
type AsyncProcessor<Transform = void> = (root: parser.Root) =>  PromiseLike<Transform>
```

Then synchronous processor functions resolve to the correct override and can call `processSync`.
