### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by ZeeCoder** [postcss/postcss-selector-parser#129]
Based on: https://github.com/postcss/postcss-nested/issues/71

Basically, postcss-nested cannot be used in browsers not supporting es6, because it depends on this package, which in turn depends on the node-specific "dot-prop" package.

**My question is:**
Is this module meant to be working in browsers?

If yes, then dot-prop would probably have to be replaced, as I don't see Sindre changing his package.
(He has a dedicated issue open on this.)
If no, then postcss-nested would probably need to find a replacement for this package, in order to have proper browser-support.

Naturally I'm more than willing to help with a PR, once a decision was reached. 👍

**Comment by ZeeCoder** [comment]
@ben-eb @chriseppstein ?
Not sure who to ping tbh

**Comment by chriseppstein** [comment]
Fixed by 92c0766f8cdb0aa3ffe39a67eaf200c875e23831
