### ISSUE TITLE
nest at rule with namespace and selector buggy

### ISSUE THREAD

**Issue by evilebottnawi** [postcss/postcss-selector-parser#130]
Input:
```css
f {
    @nest &|i {
        order: 6;
    }
}
```

Ast:
```shell
         Nesting {
           value: '&',
           source: [Object],
           sourceIndex: 0,
           spaces: [Object],
           type: 'nesting' },
         Tag {
           value: 'i',
           source: [Object],
           sourceIndex: 2,
           spaces: [Object],
           type: 'selector-tag',
           namespace: '&' } ],
      type: 'selector' }

```

Seems we have `nesting` and `namespace`.

Ref: https://github.com/jonathantneal/postcss-nesting/blob/master/test/ignore.css#L34

**Comment by evilebottnawi** [comment]
@ai Can i get invite in this repo to allow fix bugs occurring in `prettier` and `stylelint`. I set you as reviewer before merge :+1:

**Comment by ai** [comment]
I am not the maintainer. Ask @chriseppstein.

**Comment by evilebottnawi** [comment]
@chriseppstein friendly ping

**Comment by chriseppstein** [comment]
@evilebottnawi how can I help you?

**Comment by evilebottnawi** [comment]
@chriseppstein invite, for future fast fix bug for prettier and stylelint :+1:

**Comment by chriseppstein** [comment]
@evilebottnawi sent
