### ISSUE TITLE
v4 re-introduces uncompiled es6 (cssesc dep)

### ISSUE THREAD

**Issue by ZeeCoder** [postcss/postcss-selector-parser#137]
The new `cssesc` dep in v4 is uncompiled, same way `dot-prop` was previously.
Not sure what the best approach would be to keep browser compatibility, I assume the new dep cannot be dropped just like that. 🤔

**Comment by ZeeCoder** [comment]
Onthe flip-side, I've tested postcss-nested with v4, and all tests pass fine 👍

**Comment by chriseppstein** [comment]
@ZeeCoder As I understand it, the consuming app will still need to be using a bundler like webpack or rollup to publish for the web and so if cssesc were to compile to es5 with a `"browser"` entry in its `package.json` for that output, would it be sufficient? Alternatively, if the author isn't amenable to that change, I think I can do this in the postcss-selector-parser's `"browser"` field by setting it to an object with a key for `"cssesc"` pointing to a compiled version that I build here.

This functionality isn't trivial to replace, so not using it isn't an option.

**Comment by chriseppstein** [comment]
I made a pull request against `cssesc`, we'll see how that goes. https://github.com/mathiasbynens/cssesc/pull/16

**Comment by ZeeCoder** [comment]
Thanks!
Yeah I thought this would be harder to do, I like your proposed solutions though in that issue.

The main issue with this is that by default when people compile es5 => es6, they ignore the whole node_modules folder, which in this case means untranspiled code getting into your bundles. 
The future is definitely in just compiling everything, always, but as it currently is, it's still unsafe to do so.
(I heard it might be safe to do so in Babel 7 now, but I'm not sure 🤷‍♂️) 
There's also an obvious speed penalty that comes with compiling so much code.

I'll follow that issue to see how it goes. 👍

**Comment by chriseppstein** [comment]
This was fixed by changes in cssesc.

**Comment by ZeeCoder** [comment]
🎉
