### ISSUE TITLE
Umbrella issue for Prettier upgrade

### ISSUE THREAD

**Issue by duailibe** [postcss/postcss-selector-parser#142]
- [x] Attributes with spaces, i.e., `[  foo  |   attr = val   ]`. We currently support that in Prettier, maybe we could drop support?
- [x] Attributes with namespaces and unquoted value, i.e. `a[foo|bar=val]` has `raws: {}`

I'll update as I see more things, just needed a place to keep track.

cc @chriseppstein @evilebottnawi

**Comment by evilebottnawi** [comment]
Spec around spaces in attribute selector https://www.w3.org/TR/2018/CR-selectors-3-20180130/#grammar

**Comment by duailibe** [comment]
@evilebottnawi what's your opinion about it?

**Comment by evilebottnawi** [comment]
1. According spec:
- `[ foo | attr = val ]` is invalid
- `[ foo|attr = val ]` is valid
2. Better wait @chriseppstein answer

**Comment by chriseppstein** [comment]
@duailibe spaces in attributes should be handled. We have a lot of tests about it. What is the specific issue you are seeing? Can you provide input that fails and how it fails for you?

For the second item, I would not expect that to have any raws value. Why do you consider it an issue?

**Comment by chriseppstein** [comment]
Ah, yes. Space around the namespace delimiter is not allowed. Good point @evilebottnawi

**Comment by duailibe** [comment]
@chriseppstein See in [prettier playground](https://deploy-preview-4421--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEBtAZhCAfAhjGAJwF4A3XAGwF0ACYAXwB0pUabMd8izLaHnW7LHgIk248eQri+TFmw4iiEicRWTKMunMGKJXQurZqjUrf3lCINbPtFGaJ9WbayQAGhAQADjACW0ADOyKC4hIQQAO4ACmEIwSi4pBB+ACYeIABGhLhgANZwMADK3rl+UADmyEQArnCe5YFwhDDRORUAtrjI6JRNngBWgQAeAEI5+YVFuB1wADLlcD199SClhE2EyOCBwZ7ehOUwAOppMAAWyAAcAAz7EU3HOd7bB3CbpEuehHAAjjV+H5tXCdbpIXoUfogJodPzVQh1TyBcoVChwACKNQg8GWkNWMFwmVOqQuyAATJ4iLg-BQUQBhCAdLrbKDQL4gGpNAAqhISEKa9HoQA) the case that fails to format

I'm not familiar with CSS at all so I kind of expected the `raws.value` to always be present. Either way I worked around that, so it's actually a non-issue

**Comment by evilebottnawi** [comment]
```
[  foo|    attr        =        val   ] {}
[  foo |    attr        =        val   ] {}
```
invalid by spec - should be no spaces between `|`

@chriseppstein what do you think about this? I think implement speces between `|` is not diffucult, but it is invalid accroding spec

**Comment by chriseppstein** [comment]
Did prettier remove the space around the namespace delimiter? If so it would not be a regression for your users, right? (If you did leave it in, it never worked in a browser so this would also help them)

**Comment by duailibe** [comment]
> Did prettier remove the space around the namespace delimiter?

[Yes](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBtAZhCAfAhjGAJwF4A3XAGwF0ACYAXwB0pUabMd8izLaHnW7LHgIk248eQri+TFmw4iiEicRWTKMunMGKJXQurZqjUrf3lCINbPtFGaJ9WbayQAGhAQADjACW0ADOyKC4hIQQAO4ACmEIwSi4pBB+ACYeIABGhLhgANZwMADK3rl+UADmyEQArnCe5YFwhDDRORUAtrjI6JRNngBWgQAeAEI5+YVFuB1wADLlcD199SClhE2EyOCBwZ7ehOUwAOppMAAWyAAcAAz7EU3HOd7bB3CbpEuehHAAjjV+H5tXCdbpIXoUfogJodPzVQh1TyBcoVChwACKNQg8GWkNWMFwmVOqQuyAATJ4iLg-BQUQBhCAdLrbKDQL4gGpNAAqhISEKa9HoQA)

**Comment by chriseppstein** [comment]
Providing error for bad syntax is a feature of our parser.

In some cases we offer flexibility beyond the css spec, but I do not this that parsing illegal space adds value from an language extension perspective. I think it is best for this to be an error from our side

**Comment by duailibe** [comment]
@chriseppstein I did afterwards, and that's what I used to fix one broken case: https://github.com/prettier/prettier/pull/4421/files#diff-855523a43e898c253460fcf0f6e5f2a1

**Comment by chriseppstein** [comment]
@duailibe what is the black magic by which you're adding commits to my PR? I can't see the commits pushed anywhere 

https://github.com/prettier/prettier/pull/4421/commits

**Comment by duailibe** [comment]
@chriseppstein Yeah, if you enable "Allow edits from maintainers" GitHub lets us push directly to that :)

**Comment by evilebottnawi** [comment]
@chriseppstein List of changes and problems:
1. `.parent    ~` (and any combinatorics ) throw error as invalid selector. in `2` version it is works.
```scss
.parent~{
  .child-one {}
  .child-two {}
}
```

We can't handle this selector :disappointed: maybe we can reflex parser in this places?

2. `a[id=func("foo")]` doesn't parsed, but we already have discussion about this, we just output this as is in code without trying formation.

3. `html[lang=#{$locale}] {}` lose `$`, i.e. we reformat this into 
```css
html[lang="#{locale}"] {
}
```

I think it is bug

4. `node.raws.value` always exists for attribute selectors?

5. `.class !optional {}` will produce crash with memory problem

**Comment by chriseppstein** [comment]
@evilebottnawi 

1. `.parent ~` -  Seems reasonable to support this. Is this about the `~` or the fact that it ends in a combinator?
2. yeah, I can't support that selector until someone can explain why it exists and what it means. is there a specific framework that uses it? Even if I was inclined to add support for it (I'm not at the moment) I'd have to have a lot more details about what is going on here.
3. hmm. I'll investigate.
4. yeah, you're gonna need to use the new APIs for that now.
5. thanks for isolating that, I'll get it fixed.

Hopefully I can get another release candidate in the next couple days.

**Comment by evilebottnawi** [comment]
@chriseppstein 
1. Yes
2. Let's now leave as is
3. :+1: 
4. :+1: 
5: :+1: 

:+1: 

Let's first update the prettier, then, stylelint,. then cssnano and i think we can release stable version. These three packages contain a lot of tests and confirmation of the parser's stability.

**Comment by chriseppstein** [comment]
@evilebottnawi postcss-selector-parser@5.0.0-rc.2 is released with these fixes. stylelint and prettier both seem to pass with these changes.
