### ISSUE TITLE
Comments node confusing strcuture

### ISSUE THREAD

**Issue by evilebottnawi** [postcss/postcss-selector-parser#143]
Prettier have some logic around comments, also stylelint want to implement some rules for comments, one big blocker for consistently handle comments and build rules around this is difference format comment node. 

Can we use http://api.postcss.org/Comment.html for comment nodes for `5` version. It was very helpful. 
With `text`, `raw`, `source` and maybe other properties and method, Thanks!

Off topic: Also i think we should do some for postcss-value/values-parser, but it is not related to this project.

**Comment by ai** [comment]
We can keep current selector API and fix it when we will move selectors parser to the core

**Comment by evilebottnawi** [comment]
Thanks! Close in favor https://github.com/postcss/postcss-selector-parser/issues/143#issuecomment-387630850

**Comment by chriseppstein** [comment]
On the bright side, these locations for comments seem like they're not the sort of place where most devs would add a comment.
