### ISSUE TITLE
Infinite loop with unknown token

### ISSUE THREAD

**Issue by ashelley** [postcss/postcss-selector-parser#15]
This code here doesn't specify a default case and will not advance the token stream if it receives an unknown token.

https://github.com/postcss/postcss-selector-parser/blob/master/src/parser.js#L273-L302

To test this try parsing this css selector (causes an infinite loop):

```
.@test
```

The token will be 'at-word' as per:

https://github.com/postcss/postcss-selector-parser/blob/master/src/tokenize.js#L159

and will cause the parse function to loop indefinitely.  I'm not sure if we should throw here or fix the tokenizer to not push invalid tokens into the AST.

**Comment by ashelley** [comment]
I actually don't want this to throw and I want this code to ignore the problem with the css and pass through the selector so I fixed the parser like this:

```
    parse () {
        switch (this.currToken[0]) {
            case 'space':
                this.space();
                break;
            case 'comment':
                this.comment();
                break;
            case '(':
                this.parentheses();
                break;
            case '[':
                this.attribute();
                break;
            case 'word':
            case 'at-word': // basically treat this token the same as a word
                this.word();
                break;
            case ':':
                this.pseudo();
                break;
            case ',':
                this.comma();
                break;
            case '*':
                this.universal();
                break;
            case 'combinator':
                this.combinator();
                break;
        }
```

**Comment by ben-eb** [comment]
Released as `1.1.3`. Thanks for reporting. :+1:

**Comment by ashelley** [comment]
wow, that was quick! @ben-eb thanks!

**Comment by ashelley** [comment]
just a heads up that this will parse ".@something {}" into a class node with a .value of "" and a tag node with the value of .@something which may or may not be what people want.  it probably should be parsed into a class node with a .value of "@something" instead.  For now it's better than the infinite loop though.
