### ISSUE TITLE
Comment in selector

### ISSUE THREAD

**Issue by sswebcoder** [postcss/postcss-selector-parser#164]
Hello.

Can somebody explain me how process/processSync should work if string with selectors contain comment, like this: '.newbackbtn,/* .searchall, */.calNav'

I guess what nodes with comment should be exclude in toString function.

Thanks.

![image](https://user-images.githubusercontent.com/22288830/48442912-97101f80-e7a0-11e8-8522-f3d4d940eb18.png)

**Comment by evilebottnawi** [comment]
@sswebcoder why should be excluded?

**Comment by sswebcoder** [comment]
> @sswebcoder why should be excluded?

Maybe because comment is not selector?
Im not sure.

**Comment by evilebottnawi** [comment]
@sswebcoder Can you describe you problem with examples?

**Comment by sswebcoder** [comment]
> @sswebcoder Can you describe your problem with examples?

https://github.com/stylelint/stylelint/issues/3729

**Comment by evilebottnawi** [comment]
@sswebcoder hm, can yoy test with latest release?

**Comment by sswebcoder** [comment]
> @sswebcoder hm, can you test with latest release?

![image](https://user-images.githubusercontent.com/22288830/48479253-d594f100-e817-11e8-9691-ddfffe58c711.png)

**Comment by evilebottnawi** [comment]
@sswebcoder I can't understand problem, please describe what you have and what you expected and please don't use screenshots, it is hard to read and undestand

**Comment by evilebottnawi** [comment]
@sswebcoder comments should be part of ast, but it is should be comment node, we should not loss ast information

**Comment by sswebcoder** [comment]
> @sswebcoder comments should be part of ast, but it is should be comment node, we should not loss ast information

Thanks for patience and explanation.
