### ISSUE TITLE
Classes with dot within

### ISSUE THREAD

**Issue by plesiecki** [postcss/postcss-selector-parser#165]
Hello,

I would like to kindly report a issue with parser. 

For given selector `.foo\.bar` (which is valid CSS selector afaik) parser outputs two `ClassName`s: `.foo` and `.bar`.

I think the expected output in this case is a single class.

Noticed same behaviour in v4 and v5

Peace :v:

**Comment by evilebottnawi** [comment]
@plesiecki yep, it is bug, feel free to send a PR

**Comment by plesiecki** [comment]
I hope I will try someday. Any clues about this matter would be much appreciated
