### ISSUE TITLE
5.0.0 stable release?

### ISSUE THREAD

**Issue by bjankord** [postcss/postcss-selector-parser#166]
Any updates on releasing 5.0.0 stable?

**Comment by evilebottnawi** [comment]
Need fix https://github.com/postcss/postcss-selector-parser/issues/165 and we can release, feel free to send a PR

**Comment by jonathantneal** [comment]
Resolved by https://github.com/postcss/postcss-selector-parser/commit/b47e255bbcafc6b30d540b761ad6c0438ec22795
