### ISSUE TITLE
Update cssesc to 3.0?

### ISSUE THREAD

**Issue by adamwathan** [postcss/postcss-selector-parser#168]
Any chance you would be open to bumping the cssesc dependency to 3.0 for a new release?

The only change is that it drops unnecessary edge case handling that was only useful to support really old browsers, like IE6-8.

The motivation for it is explained here:

https://github.com/mathiasbynens/cssesc/issues/18

...and the actual change is here:

https://github.com/mathiasbynens/cssesc/pull/19

Thanks, this library is incredibly useful! 🙌🏻

**Comment by evilebottnawi** [comment]
@adamwathan feel free to send a PR

**Comment by adamwathan** [comment]
Done, thanks 👍
