### ISSUE TITLE
Get index of node within source string

### ISSUE THREAD

**Issue by davidtheclark** [postcss/postcss-selector-parser#18]
Right now there's a way to get the array-index of a node within its parent's node array ... but I'd like to get the string-index of a node within its source string. Is that feasible?

The use-case is for stylelint, to feed these indexes into PostCSS 5's new `warning` `index` option, in order to get accurate positions for errors (e.g. you used an id selector but have a rule saying you shouldn't).

**Comment by ben-eb** [comment]
Like PostCSS, the tokenizer does actually save source positions (e.g. https://github.com/postcss/postcss-selector-parser/blob/master/src/tokenize.js#L98), but nothing is being done about them currently. Note that as this parser is a standalone tool there probably won't be a connection between the *original* string of CSS and the location in selector-parser's AST, but you should be able to get an accurate position by comparing the two.

I don't especially want to go into the complex source-mapping that PostCSS does as this is designed to *work with* it, but we could probably do something here in regards to saving the line/column.

**Comment by davidtheclark** [comment]
I thought maybe the simplest solution would be to expose a simple string index -- and that (the index) is the info that I actually need for my use-case. Line/column wouldn't do the trick.

**Comment by ben-eb** [comment]
So if you're looking for an ID in this selector string, you would expect that this would return `4`?

```css
h1, #id {}
```

**Comment by davidtheclark** [comment]
Yes

**Comment by ben-eb** [comment]
How about `Node#sourceIndex`?

**Comment by davidtheclark** [comment]
Great!

**Comment by ben-eb** [comment]
Current work here; this is a more complex feature than I anticipated, so any help is appreciated.

https://github.com/postcss/postcss-selector-parser/tree/source-index

**Comment by davidtheclark** [comment]
Could you clarify the status of the current work? All these tests pass --- but when I look closer it seems that some of them shouldn't? Or else I don't understand? Are there more things you know need to be tested? Not sure how to contribute here.

**Comment by ben-eb** [comment]
We're currently missing support for attribute selectors and pseudo selectors. I *think* the tests that are currently there are as expected, but let me know as it's not a feature that I would personally be using. :smile:

Also, I think multi-line selectors will have some weird behaviour for `sourceIndex`; something needs to be done there to calculate how many characters need to be added. It's all OK if the selector only has 1 total line.

**Comment by davidtheclark** [comment]
Thanks! I'll probably be able to put a few minutes here and there this weekend into having a look. Hope I can figure it out.

**Comment by ben-eb** [comment]
Awesome work, thanks! :+1:

Released as `1.2.0`.
