### ISSUE TITLE
Nested pseudo selector support

### ISSUE THREAD

**Issue by ben-eb** [postcss/postcss-selector-parser#2]
We need to correctly parse/stringify these cases (and others):

```
h1:not(.heading, .title, .content)
```

```
h1:not(.heading) > h1
```

**Comment by ideadapt** [comment]
Hi

I think `h1:not(.heading, .title, .content)` is not valid css syntax. According to https://www.w3.org/TR/css3-selectors/#negation only one simple selector is allowed as argument to :not.

Ref: See https://github.com/postcss/postcss/issues/872

**Comment by ben-eb** [comment]
In level 4 of the spec, this was changed to accept a selector list.

https://drafts.csswg.org/selectors-4/#negation
