### ISSUE TITLE
support for native css mixin.

### ISSUE THREAD

**Issue by anikethsaha** [postcss/postcss-selector-parser#217]
From https://github.com/cssnano/cssnano/pull/857

I think as of now, this module and even Postcss doesn't support parsing native CSS mixin. As they are in CSS specs I guess it would be effective to support it out of the box.

**Comment by evilebottnawi** [comment]
What is spec css mixins?

**Comment by anikethsaha** [comment]
http://oocss.org/spec/css-mixins.html

Check the 1.4.2

**Comment by evilebottnawi** [comment]
It is not official css spec
