### ISSUE TITLE
No longer available on registry.yarnpkg.com

### ISSUE THREAD

**Issue by sorsaffari** [postcss/postcss-selector-parser#221]
https://registry.yarnpkg.com/postcss-Select-parser/ responds with `404`

**Comment by evilebottnawi** [comment]
Please report it to yarnpkg repo, we do not respect for it

**Comment by sorsaffari** [comment]
@evilebottnawi has this repository recently been renamed from `postcss-Select-parser`?

**Comment by evilebottnawi** [comment]
No, it is always was `postcss-selector-parser`
