### ISSUE TITLE
npm audit issue for dot-prop

### ISSUE THREAD

**Issue by Stianhn** [postcss/postcss-selector-parser#230]
[ high ] Prototype Pollution
 vulnerable versions <5.1.1 found in:
 -  devDependencies: optimize-css-assets-webpack-plugin>cssnano>cssnano-preset-default>postcss-merge-longhand>stylehacks>postcss-selector-parser>dot-prop
 -  devDependencies: optimize-css-assets-webpack-plugin>cssnano>cssnano-preset-default>postcss-merge-rules>postcss-selector-parser>dot-prop
 -  devDependencies: optimize-css-assets-webpack-plugin>cssnano>cssnano-preset-default>postcss-minify-selectors>postcss-selector-parser>dot-prop

**Comment by evilebottnawi** [comment]
Update `postcss-selector-parser` to latest version, it is fixed
