### ISSUE TITLE
 Expected a pseudo-class or pseudo-element

### ISSUE THREAD

**Issue by dimmank** [postcss/postcss-selector-parser#248]
I'm getting this error after updating from Angular v11 to v12.
Is it possible to get more error details at line 875 
if (!this.currToken) {
      return this.expected(['pseudo-class', 'pseudo-element'], this.position - 1);
}
Spent several days trying to find an error with no luck.
Are there other ways to get more information by logging out more stuff  by manually mofifying that line perhaps?

Cheers Dimitri

**Comment by alexander-akait** [comment]
In most cases you have broken CSS, I need to look at code on `875` line

**Comment by dimmank** [comment]
> In most cases you have broken CSS, I need to look at code on `875` line

Yes, it probably is, but the project is very large and have hundreds of components and scss-files.
It´s like searching for a needle in a haystack.
I have run stylelint and with no warnings and errors but still without success.

The error also points to a file that does not exists or is removed after prod build.
Error: Expected a pseudo-class or pseudo-element.
at C:\some_project_path\angular-resource-output-8.css:2:5
The selector that is throwing this error would have be nice to have printed out in the error.

Cheers!

**Comment by alexander-akait** [comment]
Can you provide source code of `angular-resource-output-8.css`?

**Comment by dimmank** [comment]
No, as a wrote above, that file cannot be found on the path printed out in the error.

**Comment by alexander-akait** [comment]
In this case I can't help, sorry

**Comment by dimmank** [comment]
Not sure if I´m being unclear here.
I just want to know how to get more error details from this parser.

Best regards Dimitri

**Comment by dimmank** [comment]
So, I found the problem that cased this error.
It was an inline style in a component.
wrong: host: { ...
correct :host { ...
