### ISSUE TITLE
Infinite loop with not and quotes

### ISSUE THREAD

**Issue by dmitry** [postcss/postcss-selector-parser#25]
This code hangs webpack:

```css
h1:not('no-anim') {
  transition: none;
}
```

Working with single or double quotes.

More details and the code to reproduce this issue: https://github.com/jtangelder/sass-loader/issues/168

I believe it should never hang in the infinite loop, but rather use limited number of iterations to complete the parsing and may be raise an error.

This test code should work:

```
test('negation pseudo element with quotes', 'h1:not(".heading")', (t, tree) => {
    t.plan(2);
    t.equal(tree.nodes[0].nodes[1].value, ':not');
    t.equal(tree.nodes[0].nodes[1].nodes[0].nodes[0].value, 'heading');
});
```

**Comment by ben-eb** [comment]
Released as 1.3.0, thanks for reporting. :+1:

**Comment by dmitry** [comment]
@ben-eb Thanks! :rocket:

Does it works with single-quote? I don't see the tests for that.

**Comment by ben-eb** [comment]
Yep, it uses the same string tokenizing logic as PostCSS. I added a test case in 37750c7.

**Comment by dmitry** [comment]
@ben-eb thanks again! :+1:
