### ISSUE TITLE
infinite loop when using processSync with some css selectors that has "|"

### ISSUE THREAD

**Issue by mostafa-hisham** [postcss/postcss-selector-parser#266]
when using `processSync` on css rules contains `|` Leeds to infinite loops
some rules examples
```
.example1,|#example2{
color:red
}

*|:{font-size:10px}

| .example{
color:blue;
}
```

**Comment by alexander-akait** [comment]
Sounds like a bug, feel free to send a fix

**Comment by iskandar-aptiv** [comment]
seems missed to update position when when  pipe is detected`|` here https://github.com/postcss/postcss-selector-parser/blob/master/src/parser.js#L518

**Comment by romainmenke** [comment]
What is the expectation here?

Is `|` a non-standard combinator, a word, or do we throw an error?

All the examples given are invalid selectors, neither column combinators, nor namespaces.
