### ISSUE TITLE
Throw on trailing colons?

### ISSUE THREAD

**Issue by ben-eb** [postcss/postcss-selector-parser#27]
Currently we do this, as it turns out it breaks support for Polymer mixins, see: https://github.com/ben-eb/gulp-cssnano/issues/17.

How should we handle these in future? Should we still throw or parse them as a type?

/cc @davidtheclark

**Comment by davidtheclark** [comment]
> parse them as a type

Does that mean `--something:` would have *two* type selectors, `--something` and `:`? Or that the whole thing would be one type selector?

The weird thing that I'm trying to get about the Polymer syntax is that it's mimicking custom properties -- so it's actually not intended to be a selector, I think, but a custom property -- but it doesn't look like they're applying it to `:root`. What I'm saying is I'm not sure that should be parsed as a selector.

If Polymer users put they're custom-property-mixin-declarations in `:root` rules, this would be a non-issue, right?

**Comment by ben-eb** [comment]
*Not* parsing these is much more acceptable, I think. I chose to ignore these "selectors" in postcss-minify-selectors so my use case is covered, but I wanted a second opinion. Thanks!
