### ISSUE TITLE
Breaking change: the each method executes one extra time in version 7.0.0

### ISSUE THREAD

**Issue by edison1105** [postcss/postcss-selector-parser#297]
In version `6.1.2`, the following code outputs `1`, but in version `7.0.0`, it outputs `2`. 
The reason is that `selector.each` executes once more after `insertAfter`. 
This caused an issue for Vue when [upgrading to postcss-selector-parser v7](https://github.com/vuejs/core/pull/12279)

minimal reproduction link: https://github.com/edison1105/postcss-selector-parser-bug

```js
const parser = require('postcss-selector-parser');
const postcss = require('postcss')

let count = 0
const transform = selectors => {
    selectors.each(selector => {
        selector.each(n => {
            count++
            if (n.nodes) {
                selectors.insertAfter(selector, n.nodes[0])
                selectors.removeChild(selector)
            }
        })
    })
}

function processRule(rule) {
    rule.selector = parser(transform).processSync(rule.selector);
}

const plugin = {
    postcssPlugin: 'postcss-plugin',
    Rule(rule) {
        processRule(rule)
    },
}

postcss([plugin]).process(':global(.foo) { color: red; }').then(result => {
    console.log('count:', count)
});

```

**Comment by romainmenke** [comment]
Hi @edison1105,

This is exactly what was changes and why it was released as a major version.
Is this something you can resolve in Vue itself by updating your internal logic?

For example by using `selectors.replaceWith(n.nodes[0])` ?

**Comment by edison1105** [comment]
Thanks for your response. Since this is expected, I will try to modify the internal logic of Vue. I think `selectors.replaceWith(n.nodes[0])` should solve the problem
