### ISSUE TITLE
sourceIndex on selector nodes

### ISSUE THREAD

**Issue by davidtheclark** [postcss/postcss-selector-parser#36]
I just noticed that `sourceIndex` is `undefined` on selector nodes. Seems like selectors nodes should get that data just like the other nodes.

A use-case is to get the index of one selector within a selector list: I might parse the selector list `.foo .bar .baz, a b`, then run `selectorListNode.each(selectorNode => {..})` and within that function want to know `selectorNode.sourceIndex`.

Just a feature idea.

**Comment by ben-eb** [comment]
PR welcome. :+1:

**Comment by chriseppstein** [comment]
Added in 783e2eca39dcefa6b9bba07c2e5feb3558478116. Thanks @davidtheclark
