### ISSUE TITLE
Parser seems to hang on mismatched closing parenthesis

### ISSUE THREAD

**Issue by jeddy3** [postcss/postcss-selector-parser#42]
Ref: https://github.com/stylelint/stylelint/issues/848

```js
var parser = require("postcss-selector-parser")
var result = parser().process(')').result
var result = parser().process('a(b))').result
// etc...
```

I spent a while looking through the source of the parser (which was very informative, but a bit beyond me I'm afraid) and I think it might have something to do with [these while loops](https://github.com/postcss/postcss-selector-parser/blob/master/src/parser.js#L180). Sorry for not being more help though.

Any idea what is causing the hang?

**Comment by ben-eb** [comment]
Seems like it would be appropriate to throw an error in these cases as they aren't valid selectors, what do you think?

**Comment by jeddy3** [comment]
I think so.

FYI, I stuck at it for a while I got as far as splitWord in parser.js. I'm curious to see where throwing this error goes as it might help me understand the mechanics a bit better.

**Comment by ben-eb** [comment]
It hangs because the closing parenthesis is not handled by the `loop` function. :smile:

**Comment by jeddy3** [comment]
I was getting closer :-)
