### ISSUE TITLE
Test failures on 0.12

### ISSUE THREAD

**Issue by ben-eb** [postcss/postcss-selector-parser#44]
Cannot reproduce locally, need to find out the cause of the error (blocking v2).

https://travis-ci.org/postcss/postcss-selector-parser/jobs/114067641
https://travis-ci.org/postcss/postcss-selector-parser/jobs/114086067

/cc @davidtheclark @jeddy3

**Comment by jeddy3** [comment]
Can you try a more verbose (`-v`) ava output on travis?

**Comment by ben-eb** [comment]
Yeah, it didn't yield any different output unfortunately.

https://travis-ci.org/postcss/postcss-selector-parser/jobs/114115968

**Comment by davidtheclark** [comment]
I also was unable to reproduce by switching Node versions. That's on OSX. I will be on a Linux machine at work tomorrow and can see if that makes a difference and I'm able to reproduce.

**Comment by ben-eb** [comment]
@davidtheclark Thanks! Just really puzzled why this is happening. :confused:

**Comment by davidtheclark** [comment]
Sorry forgot to follow up on this. No good news, though. I cannot reproduce on Linux, either.

**Comment by ben-eb** [comment]
@davidtheclark No problem, this is also tracked here: https://github.com/sindresorhus/ava/issues/604
