### ISSUE TITLE
Ideas for API, anything else we should add?

### ISSUE THREAD

**Issue by ben-eb** [postcss/postcss-selector-parser#5]
Some of my initial thoughts on this:

# ast methods

## each (done)

Non-recursive iterator for each selector inside a container.

## eachInside (done)

Recursive iterator for each selector inside a container.

```js
selectors.eachInside(function (selector) {
    if (selector.type === 'class' && selector.value === 'c') {
        var attr = parser.attribute({value: 'c', operator: '=', attribute: 'data-attr'});
        selector.replaceWith(attr);
    }
});
```

## eachClass (done)

Sugar for `eachInside`.

```js
selectors.eachClass(function (selector) {
    if (selector.value === 'c') {
        var attr = parser.attribute({value: 'c', operator: '=', attribute: 'data-attr'});
        selector.replaceWith(attr);
    }
});
```
## split (done)

```js
var list = selectors.split(function (selector) {
    return selector.combinator === '>>';
});
```

## last (done)

# parser methods

## attribute (done)

```js
var attr = parser.attribute({value: 'c', operator: '=', attribute: 'data-attr'});
// => [data-attr=c]
```

## class (done)

```js
var class = parser.class({value: 'c'});
// => .c
```

## comment (done)

```js
var comment = parser.comment({value: '/* c */'});
// => /* c */
```

## id (done)

```js
var id = parser.id({value: 'c'});
// => #c
```

## pseudo (done)

```js
var pseudo = parser.pseudo({value: '::c'});
// => ::c
```

## tag (done)

```js
var tag = parser.tag({value: 'c'});
// => c
```

## universal (done)

```js
var universal = parser.universal();
// => *
```

## fromString

Create a new node by parsing the string and returning the appropriate node.

```js
var attr = parser.fromString('[data-attr=c]');
// => [data-attr=c]
```

**Comment by TrySound** [comment]
@ben-eb If something like this is possible, I do not have suggestions.
```js
inst.eachClass(function (rule) {
  if(rule.name === 'c') {
    rule.replaceWith('[data-attr=c]');
  }
});
```

**Comment by ben-eb** [comment]
@TrySound Yes, I plan to do something like this. I think `eachClass` should be just sugar for `eachInside`, so this would also be equivalent:

```js
selectors.eachInside(function (selector) {
    if (selector.type === 'class' && selector.value === 'c') {
        var attr = parser.attribute({value: c, operator: '=', attribute: 'data-attr'})
        selector.replaceWith(attr);
    }
});
```

**Comment by benfrain** [comment]
Ben, one thing I intend to add to my workflow shortly is the ability to warn or error if certain class naming conventions (via regexp) are not met. Looks like the eachClass would be good for that?

**Comment by ben-eb** [comment]
@benfrain Yep, that sounds like a good use case for this API. It could look something like this:

```js
selectors.eachClass(function (selector) {
    if (/[^a-z]/.test(selector.value)) {
        throw new Error(selector.value + ' is not a valid class name');
    }
});
```

I am not sure about warnings/errors API for this just yet, however. I think it is probably best to use the PostCSS warnings API after parsing the selector, so that you get a position of the error.

**Comment by MadLittleMods** [comment]
#### `eachDescendent`

`a b c` or `a >> b >> c`

 - `a`
 - `b`
 - `c`


#### `eachDirectDescendent`

`a > b c > d + e`

 - `a`
 - `b c`
 - `d + e`

Maybe a `eachCombinator(combinator, cb)`

#### `eachCompoundSelector`

`h2 a[href] i:not([alt])`

 - `h2`
 - `a[href]`
 - `i:not([alt])`

**Comment by ben-eb** [comment]
@MadLittleMods These can be handled by `eachInside`. In the case of `eachCompoundSelector`, `eachInside` could iterate:

* `h2`
* `a`
* `[href]`
* `i`
* `:not()`
* `[alt]`

I'm considering adding `eachCombinator`. However it would probably end up as sugar for this:

```js
selectors.eachInside(function (selector) {
    selector.combinator = '>>';
});
```

**Comment by ben-eb** [comment]
@MadLittleMods suggested this in the Gitter chat:

```
selector.splitAtCombinator('>>').forEach()
```

**Comment by ben-eb** [comment]
I have `replaceWith` still left to do, and will provide `insertBefore` & `insertAfter` methods to work with that. After these are done I will release a `1.0.0` version.

Any other suggestions for this initial API?

**Comment by ben-eb** [comment]
Done https://github.com/postcss/postcss-selector-parser/commit/86137dfb872b8200e8dfca74533269b0b67807e0.

**Comment by Semigradsky** [comment]
Looks like many of this methods not represented in [API](https://github.com/postcss/postcss-selector-parser/blob/master/API.md)

**Comment by thomasklein** [comment]
Also not working. Trying 
`
parser(function (selectors) {
      selectors.eachUniversal(function (selector) {});
});
`
However I end up with a TypeError `selectors.eachUniversal is not a function`
Using postcss 5.1.2 and postcss-selector-parser 2.2.0.

**Comment by ben-eb** [comment]
Guys, this is a year old *closed* thread discussing the *original* API. This was back when postcss 4 was out and I wanted to mirror that API. We're now on a more PostCSS 5-like API; check out the docs here - https://github.com/postcss/postcss-selector-parser/blob/master/API.md
