### ISSUE TITLE
tag selectors with attributes lose quotation marks

### ISSUE THREAD

**Issue by shellscape** [postcss/postcss-selector-parser#50]
It would seem that the parser isn't considering the quotation marks used in selectors, specifically tag selectors with attribute definitions.

Consider the following selector: `input[type='text']`

The parsed tree output for that selector is:

```js
Selector {
  spaces: { before: '', after: '' },
  nodes: 
   [ Tag {
       value: 'input',
       source: [Object],
       sourceIndex: 0,
       spaces: [Object],
       type: 'tag',
       parent: [Circular] },
     Attribute {
       operator: '=',
       value: '\'text\'',
       source: [Object],
       sourceIndex: 5,
       attribute: 'type',
       spaces: [Object],
       type: 'attribute',
       raw: {},
       parent: [Circular] } ],
  type: 'selector',
  parent: 
   Root {
     spaces: { before: '', after: '' },
     nodes: [ [Circular] ],
     type: 'root' } }
```

I had the expectation that the quotation marks would be preserved in raws or spaces, or some other property.

**Comment by ben-eb** [comment]
The quotation marks appear in the attribute value property.

**Comment by shellscape** [comment]
ouch, not even a chance for discussion.

other ast generators treat non-word characters like quotation marks like metadata, or akin to how postcss treats spacing around properties and values. this would be a big value-add for granular inspection of selectors.

**Comment by ben-eb** [comment]
What use case do you have in mind? The way it works now may be a little naïve but I haven't had reason to change it. :smile:

**Comment by shellscape** [comment]
thanks for reopening. here's our exact use case: https://github.com/lesshint/lesshint/blob/postcss-less-parser-replacement/lib/linters/attribute_quotes.js#L15

The `attribute` property contains the string value, minus the quotations just as we had expected. We'd love to be able to walk or inspect the quotations around it, rather than using a regex on the entire string. That's why I had initially thought the `raws` property would have been ideal for containing that bit.

**Comment by ben-eb** [comment]
/cc @jeddy3 @davidtheclark @ai 

Thoughts?

**Comment by davidtheclark** [comment]
Makes sense to me to have it in `raw` or as an additional property, either way.

**Comment by jeddy3** [comment]
If having it in `raw` etc allows a more granular inspection, then that sounds good to me.

**Comment by ben-eb** [comment]
My opinion on this is that the quotes are *either* optional *or* mandatory, depending on what characters are in the value and, as they can be either `"` or `'` it makes the most sense to me to have them as part of the value.

My proposed solution would be to provide a `quoted` (boolean) property in the attribute selector, with an `unquoted` property in the raw values as a convenience. What do you guys think?

**Comment by shellscape** [comment]
`raws` in postcss does have several optional properties that will exist based on the situation or node type, and data for that node. going with that pattern, having the quotes represented in `raws` would seem to be acceptable on the surface.

I think the `quoted` property would be great, but is still limiting. For our use-case, we're using this with a LESS linting toolset (lesshint) and need to know what type of quote they are. We're using a regex right now to inspect the quotes on the value itself, but having the quote character in a property makes that kind of inspection far easier (and ever so slightly more performant)

**Comment by ben-eb** [comment]
With this proposed change you could also do this:

```js
if (attr.quoted) {
  var quoteType = attr.value.slice(0, 1);
}
```

**Comment by shellscape** [comment]
sure, that'd work as well.

**Comment by ben-eb** [comment]
OK. PR welcome for this. :+1:

**Comment by shellscape** [comment]
I'm working on a complete rewrite of postcss-value-parser (based on this project) at the moment. If no one gets to this by the time I finish, I'll give it a shot.

**Comment by shellscape** [comment]
thanks @davidtheclark and @ben-eb
