### ISSUE TITLE
please publish new minor

### ISSUE THREAD

**Issue by shellscape** [postcss/postcss-selector-parser#51]
cheers on this parser, very well done thus far. I'd like to request a new minor version be published with the changes from `eachAttribute` -> `walkAttributes`. I was using the source as a reference and couldn't figure out why walk and walkAttributes were undefined. Version 1.3.3 doesn't contain those references, but rather `each` and `eachAttribute`.

thanks again

**Comment by ben-eb** [comment]
It's a breaking change so I can't release a minor. This release is unfortunately blocked at the moment, as we're getting random failures on 0.12.

https://github.com/postcss/postcss-selector-parser/issues/44
