### ISSUE TITLE
Handling of Sass interpolation

### ISSUE THREAD

**Issue by davidtheclark** [postcss/postcss-selector-parser#52]
I thought we must have discussed this before but can't find any record ... So here's the issue (cf. https://github.com/stylelint/stylelint/issues/945):

If Sass users have `.#{$my-class-name}` that selector gets parsed as a class simple selector (with no actual class name) and an id simple selector. What would you think about changing the behavior so `#` does not trigger the beginning of an id selector if it is immediately followed by `{`?

No legit id (that actually works) can have a `{` there, I believe.

**Comment by ben-eb** [comment]
What's the *ideal* expected result from the parser for this selector?

We can change this for 2.0 if you like. It's still blocked...

**Comment by davidtheclark** [comment]
I think just treating it as a class with a value of `#{$my-class-name}`, so the user can decide what to do with it. Sound good?

**Comment by ben-eb** [comment]
OK. PR welcome. :+1:
