### ISSUE TITLE
raws versus raw

### ISSUE THREAD

**Issue by shellscape** [postcss/postcss-selector-parser#54]
Wanted to raise this slight discrepancy with the PostCSS main parser. postcss-selector-parser uses a property name of `raw` on its nodes, while PostCSS uses the property name `raws` on its nodes. Surely nothing critical, but would be keen to see a consensus reached so this could be merged as part of PostCSS proper, and also for ease of development in other tools.

**Comment by ben-eb** [comment]
Yeah, 5.0 introduced `raws`. We can do the same for `2.0`, not really concerned too much about the name to be honest.

**Comment by shellscape** [comment]
:+1:  just wanted to put it on the radar
