### ISSUE TITLE
Release version 2.0

### ISSUE THREAD

**Issue by clentfort** [postcss/postcss-selector-parser#58]
Is there an ETA when version 2.0 will be push to npm? The docs are ahead of the currently released version. This lead to some confusion on my side why `walk` etc were undefined on the containers.

**Comment by ben-eb** [comment]
Not until the issues in the milestone are resolved.

https://github.com/postcss/postcss-selector-parser/milestones/2.0

**Comment by ben-eb** [comment]
I think we're almost there, just waiting for some confirmation on https://github.com/postcss/postcss-selector-parser/pull/35.

**Comment by ben-eb** [comment]
Done. https://github.com/postcss/postcss-selector-parser/commit/1b204ce18de12172ef57aec8682f8d503b54deb3
