### ISSUE TITLE
Whitespace handling

### ISSUE THREAD

**Issue by ben-eb** [postcss/postcss-selector-parser#6]
The whitespace handling is currently not fantastic. I believe that it is throwing off the parsing for nested pseudo elements, so I would like to change it. I am considering this new structure (consider SS as spaces):

```css
SSh1SSSSh2SS
```

Parsed to:

```js
spaces: {
    before: '  ',
    after: '  ',
},
combinator: ' ',
raw: {
    combinator: '    '
}
```

This way `combinator` should always contain the 'cleaned' version of the whitespace, and `raw` can contain the original amount.

**Comment by MadLittleMods** [comment]
**Note:** For this idea, flatten out combinator into its own node alongside others.

 - Put before/after `spaces` in preceding/following nodes.
 - For the special case of the `space` descendant combinator, use the first or last space between the nodes. 

#### `h1     >>      h2`

```
[
	{
		type: 'tag',
		value: 'h1',
		spaces: {
			before: '',
			after: '     '
		}
	},
	{
		type: 'combinator',
		value: '>>'
	},
	{
		type: 'tag',
		value: 'h2',
		spaces: {
			before: '      ',
			after: ''
		}
	}
]
```

#### `h1           h2`

```
[
	{
		type: 'tag',
		value: 'h1',
		spaces: {
			before: '',
			after: ''
		}
	},
	{
		type: 'combinator',
		value: ' '
	},
	{
		type: 'tag',
		value: 'h2',
		spaces: {
			before: '          ',
			after: ''
		}
	}
]
```

**Comment by ben-eb** [comment]
Most of the work for this landed in https://github.com/postcss/postcss-selector-parser/commit/30b08d52c9efd3c68c88791ecf2b933bf6bbfa56. I am going to refactor how other (non combinating) spaces are handled and then I'll go ahead and close this.
