### ISSUE TITLE
Error thrown when using nested Sass property syntax

### ISSUE THREAD

**Issue by stickel** [postcss/postcss-selector-parser#64]
I'm running into this error message when I call `stylelint` on uncompiled Sass files in my project. `stylelint` uses `postcss-scss` which in turn uses `postcss-selector-parser`.

``` shell
Error: Expected pseudo-class or pseudo-element
    at new error (/project/node_modules/postcss-selector-parser/dist/processor.js:27:23)
    at Parser.error (/project/node_modules/postcss-selector-parser/dist/parser.js:212:15)
    at Parser.pseudo (/project/node_modules/postcss-selector-parser/dist/parser.js:292:25)
    at Parser.parse (/project/node_modules/postcss-selector-parser/dist/parser.js:502:22)
    at Parser.loop (/project/node_modules/postcss-selector-parser/dist/parser.js:470:18)
    at new Parser (/project/node_modules/postcss-selector-parser/dist/parser.js:89:21)
    at Processor.process (/project/node_modules/postcss-selector-parser/dist/processor.js:24:21)
    at /project/node_modules/stylelint/dist/rules/selector-pseudo-element-case/index.js:48:10
    at /project/node_modules/postcss/lib/container.js:110:28
    at /project/node_modules/postcss/lib/container.js:73:26
```

After some digging, the error occurs when a Sass stylesheet has the following syntax:

``` scss
.foo {
  flex: {
    grow: 1;
    shrink: 1;
  }
}
```

Which compiles to:

``` css
.foo {
  flex-grow: 1;
  flex-shrink: 1;
}
```

The same error occurs with `font: { size: 12px; weight: bold; }` (and likely other nested properties). When this type of nesting is removed from the Sass file no error is reported.

**Comment by s10wen** [comment]
Looks like this issue was closed, but I'm also getting it: https://github.com/stylelint/stylelint/issues/1386#issuecomment-223266044

**Comment by ben-eb** [comment]
The reason that this throws is because for example `a:` is not a valid CSS selector (whereas `a:before` *is*); this module expects to receive one or many CSS selectors and does some basic validation to ensure that a selector is valid. It's kind of related to https://github.com/stylelint/stylelint/issues/1153.

**Comment by s10wen** [comment]
Thanks @ben-eb I'm specifically using `stylelint` for `.scss` files. Can you point me in the direction of a solution?

**Comment by ben-eb** [comment]
I believe this should be handled in stylelint; I have done the same thing with postcss-minify-selectors, in which I handle the case where a property ends with a colon;

https://github.com/ben-eb/postcss-minify-selectors/blob/master/src/index.js#L15-L19

**Comment by s10wen** [comment]
thanks @ben-eb I'll take a look.

**Comment by brneto** [comment]
So, scss nested properties still not working in stylelint?
