### ISSUE TITLE
Async support

### ISSUE THREAD

**Issue by jacobp100** [postcss/postcss-selector-parser#66]
If the function passed to `parser` returns a promise, it would be good to await that promise, and return a promise with the result.

The example in the readme would then become,

``` js
var parser = require('postcss-selector-parser');
var transform = async function (selectors) {
    selectors.eachInside(function (selector) {
        // do something with the selector
        console.log(String(selector))
    });
};

var transformed = parser(transform).process('h1, h2, h3').then(result => ...);
```

_Should_ be backwards compatible.

**Comment by jacobp100** [comment]
https://github.com/postcss/postcss-selector-parser/pull/67

**Comment by ben-eb** [comment]
https://github.com/postcss/postcss-selector-parser/releases/tag/v3.0.0-rc.0
