### ISSUE TITLE
"Lossy" mode.

### ISSUE THREAD

**Issue by ben-eb** [postcss/postcss-selector-parser#7]
For most use cases I feel it is appropriate for the parser to be able to normalize whitespace values itself, but only if the consumer tells it to. In the case of a linter, for example, you might want to show a warning that there is extra whitespace, but for everything else we can tell the parser to discard the `raw` property. So to enable this I was thinking of this API:

```js
parser(func).process(string, {lossless: false})
```

So an input like this:

```css
h1         h2
```

Would be normalized in this mode to:

```css
h1 h2
```

**Comment by ai** [comment]
Why it should be in parser? Lets normalize in plugin, like we do it in PostCSS.

**Comment by ben-eb** [comment]
@ai It should only be a shortcut so that the user doesn't have to care about the raw property. I don't see any harm in adding it, especially as the parser can tell which whitespace is significant and which isn't.

**Comment by adam-26** [comment]
Hi @ben-eb, has there been any progress on this? If not, do you have any guidance on how would you implement it? I require this functionality, maybe I can submit a PR.

**Comment by ben-eb** [comment]
@adam-26 No, if you would like to take this issue it would be appreciated! My idea was basically to skip adding *insignificant* spaces and raw properties to the AST in this mode, so for example these lines would not be executed;

* https://github.com/postcss/postcss-selector-parser/blob/master/src/parser.js#L83
* https://github.com/postcss/postcss-selector-parser/blob/master/src/parser.js#L296
* https://github.com/postcss/postcss-selector-parser/blob/master/src/parser.js#L498-L501

I'm not sure if this is that easy anymore given that we now maintain source positions for each node.

By the way if you need just the functionality of normalizing the selector you could check out https://github.com/ben-eb/postcss-minify-selectors.

**Comment by adam-26** [comment]
Hi @ben-eb, postcss-minify-selectors does most of what I require without having to modify the parser, which is great. Thanks for posting the link, and thanks for all the work on postcss :)

**Comment by ben-eb** [comment]
Fixed by https://github.com/postcss/postcss-selector-parser/pull/81#issuecomment-238033015.
