### ISSUE TITLE
Support pseudo-classes anywhere in selector

### ISSUE THREAD

**Issue by davidtheclark** [postcss/postcss-selector-parser#8]
The following tests do not pass but should (I think):

```js
test('pseudo class not at the end of the selector chain', 'a:link.external', (t, tree) => {
    t.plan(6);
    t.equal(tree.nodes[0].nodes[0].type, 'tag');
    t.equal(tree.nodes[0].nodes[0].value, 'a');
    t.equal(tree.nodes[0].nodes[1].type, 'pseudo');
    t.equal(tree.nodes[0].nodes[1].value, ':link');
    t.equal(tree.nodes[0].nodes[2].type, 'class');
    t.equal(tree.nodes[0].nodes[2].value, 'external');
});
```

(I didn't know if you would want me to submit a PR with breaking tests.)

It is more typical to apply pseudo-classes at the end of a selector, but I guess it is not required:

> Pseudo-classes are allowed anywhere in selectors while pseudo-elements may only be appended after the last simple selector of the selector.

(http://www.w3.org/TR/CSS21/selector.html%23id-selectors#pseudo-elements)

The tested selector above is from http://meyerweb.com/eric/articles/webrev/200102.html.

**Comment by ben-eb** [comment]
The behaviour as it stands is intended for pseudo-elements. However I don't think in the parser we should differentiate between types of pseudo selectors, so I am happy to accept a PR for this. :+1:

**Comment by ben-eb** [comment]
@davidtheclark The tests are not passing because the word splitting logic only exists in the `word` function. So I think this patch needs to extract that out into some common method that the `word` and `pseudo` function can both consume.

**Comment by davidtheclark** [comment]
Ok, thanks for the info. At some point within the next week I will try to find some time to look into this.

**Comment by davidtheclark** [comment]
I'm finding it pretty difficult to figure out what's going on in there ... so just an FYI that this may be a while.

**Comment by ben-eb** [comment]
I don't mind doing this if you are struggling with it. I know this parser quite well now. :smile:

**Comment by davidtheclark** [comment]
Go for it. I'm not making a lot of progress here. I'll try to understand your solution.
