### ISSUE TITLE
Error throw when using UglifyJsPlugin with webpack

### ISSUE THREAD

**Issue by AceLeeWinnie** [postcss/postcss-selector-parser#80]
When I compress package in product environment,  a error message thrown.

> ERROR in ./~/css-loader!./src/com/modal/legacy/modals/Modal.css
> Module build failed: Error: Expected opening square bracket.
>   at process._tickDomainCallback (internal/process/next_tick.js:129:7)

I wonder if any the css file minify or uglify twice and result the error.

**Comment by ben-eb** [comment]
Hi,

This error is thrown when there is an extra closing square bracket `]` is encountered (and the parser hasn't found the opening square bracket `[` to "close" the pair). I think you have a syntax error in your original CSS file.

**Comment by AceLeeWinnie** [comment]
But in other environment, there's no error thrown.  I wonder if the file compressed twice.

**Comment by ben-eb** [comment]
I'm not sure exactly; I would need more information on how this is happening. It would be really useful if you could put together a sample repository that exhibits this issue. :smile:

**Comment by blowsie** [comment]
I think the node version my impact this

**Comment by ben-eb** [comment]
https://github.com/postcss/postcss-selector-parser/releases/tag/v3.0.0-rc.0
