### ISSUE TITLE
Inserting inside iterators

### ISSUE THREAD

**Issue by pascalduez** [postcss/postcss-selector-parser#86]
Hi,

trying to insert a new selector node inside a container while looping over it seems to stop the loop.

``` js

const parser = require('postcss-selector-parser');

const selectors = 'ul li, nav a';


const transform = selectors => {
  selectors.each(sel => {
    let foobar = parser.className({ value: 'foobar' });
    sel.parent.insertAfter(sel, foobar);
  });
};

const result = parser(transform).process(selectors).result;

console.log(result);
```

Expected:

``` css
ul li, .foobar, nav a, .foobar
```

Result:

``` css
ul li, .foobar, nav a
```

Is this intended?

**Comment by ben-eb** [comment]
Hi,

I think this might be a bug, but I'm not sure of the source of the issue to be honest. 😕

**Comment by pascalduez** [comment]
Hey,

all right, I will try to dive a bit more in when working back on the project involved with it.

**Comment by tivac** [comment]
Replacing inside iterators is also broken.

https://repl.it/HIvF/3

I'm looking into why, seems like `.each()` is getting cranky.

**Comment by chriseppstein** [comment]
I hit this today and it tripped me up for a while. Was able to work around by saving references and doing mutation after the iteration was over.

**Comment by tivac** [comment]
@chriseppstein yeah, that's what https://github.com/tivac/modular-css/pull/278 is doing. Hopefully @ben-eb can find some time to check out #105 and get that merged (if it's good) before too much longer.

**Comment by ben-eb** [comment]
https://github.com/postcss/postcss-selector-parser/releases/tag/v3.0.0-rc.0
