### ISSUE TITLE
exist is not defined

### ISSUE THREAD

**Issue by jonathantneal** [postcss/postcss-selector-parser#9]
It makes using `insertBefore` and `insertAfter` rather impossible.

https://github.com/postcss/postcss-selector-parser/blob/master/src/selectors/container.js#L81

**Comment by ben-eb** [comment]
:+1: 

Surprised the tests didn't pick this up. :confused:

**Comment by ben-eb** [comment]
@jonathantneal Can you provide some example code that I could reproduce this with? I have this test passing:

```js
test('container#insertAfter (during iteration)', (t) => {
    t.plan(1);
    let out = parse('h1, h2, h3', (selectors) => {
        selectors.eachTag(function (selector) {
            let attribute = parser.attribute({attribute: 'class'});
            selector.parent.insertAfter(selector, attribute);
        });
    });
    t.equal(out, 'h1[class], h2[class], h3[class]');
});
```

**Comment by ben-eb** [comment]
Released as `1.0.1`.

**Comment by jonathantneal** [comment]
Thanks so much for the fix! I’ll use the proper methods in my plugin as soon as I can.

I am matching the `:any-link` pseudo-class in a selector, and then replacing that selector with the two fallbacks which use `:link` and `:visitied` in its place. To get around this bug, I ended up using `selectors.node.splice` for my first release.

https://github.com/jonathantneal/postcss-pseudo-class-any-link/blob/master/index.js#L20

**Comment by ben-eb** [comment]
Nice one. Let me know if there are any other issues, this parser is still very early days at the moment! :smile:
