### ISSUE TITLE
Quick question: does it support grunt-postcss?

### ISSUE THREAD

**Issue by michaelkdh** [postcss/postcss-selector-parser#90]
Trying to rename every single class name with a prefix, any advises?

**Comment by ben-eb** [comment]
Hi,

This is a utility intended to be used by a PostCSS plugin - it isn't itself a PostCSS plugin. But you could use this module *in* a PostCSS plugin to achieve this. 😄

**Comment by michaelkdh** [comment]
Yes, it does

**Comment by michaelkdh** [comment]
Thanks Ben, that's exactly what i did, cheers.
